### ISSUE TITLE
More spam ads on s7 about clothing. Website could potentially crash again. Fix it please.

### ISSUE THREAD

**Issue by raptor200221** [rkuykendall/Simplici7y#10]
There are more spammers. Please fix this. The particular user this time is oseptonulys. Most likely the same guy who crashed the website last time.

**Comment by rkuykendall** [comment]
Fixed. S7 does not currently support a re-captcha, which is the source of this problem. We could and maybe should add one. I'm working on a few solutions to this. Hopefully the spammers don't prevent enough of a problem in the mean-time. Closing this issue as it's not about re-captcha, but about the spammer, who is deleted. Feel free to open another.
