### ISSUE TITLE
Cannot set tags on an uploaded item

### ISSUE THREAD

**Issue by Shappie112** [rkuykendall/Simplici7y#13]
Seen here, http://simplici7y.com/items/marathon-apotheosis

I was having issues uploading it in the first place because it kept bringing me to the "Congratulations, you found a bug!" page. This lead me to believe the items weren't being created, but they were.

After I got it set up, I noticed the tags I had set were blank. Whenever I go to edit the item and add the tags, I'm brought back to the error page. I'm guessing this is why I was seeing the error during the item creation step as well.

**Comment by Shappie112** [comment]
Nevermind, I'm an idiot.

**Comment by rkuykendall** [comment]
Thanks for the report anyways @Shappie112! The error reporting on S7 is awful so I'm sure it wasn't your fault. Thanks for the report!
