### ISSUE TITLE
Feature Request: RSS

### ISSUE THREAD

**Issue by JoshuaPettus** [rkuykendall/Simplici7y#17]
Not important, but it has been a real nice to have on the old version

**Comment by rkuykendall** [comment]
The RSS feeds have been restored! Thank you for the issue / feature requrest.

<img width="49%" alt="image" src="https://github.com/rkuykendall/Simplici7y/assets/796717/d37d59f4-47d7-4ecb-af25-a157143ed790"><img width="49%" alt="image" src="https://github.com/rkuykendall/Simplici7y/assets/796717/9b9c9bdc-a31c-4b67-842a-f6c780fa5957">

**Comment by JoshuaPettus** [comment]
thank-you! works great!
