### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by sfiera** [rkuykendall/Simplici7y#19]
There’s no license in the repository, so although [the Simplici7y page for itself](https://simplici7y.com/items/simplici7y/) has an `opensource` tag it’s not clear whether Simplici7y is open source or not.

GitHub has a [license wizard](https://github.com/rkuykendall/Simplici7y/community/license/new) for adding one. I have no particular opinion about the appropriate license, though I note [Aleph One is GPLv3](https://github.com/Aleph-One-Marathon/alephone/blob/master/COPYING).

**Comment by rkuykendall** [comment]
Thanks for this @sfiera. Your recent commit inspired me to [clean up the codebase for contributors](https://github.com/rkuykendall/Simplici7y/commit/57e96ebb2868394b7413cea02cda456b5b12c091). I asked @treellama if he has any opinions on license but if not I'll just pick MIT as it seems the most permissive.

**Comment by treellama** [comment]
I think it depends mostly on your taste. MIT is good for "do whatever you want just credit me." GPL (what I use for Weland and Aleph One" is more "do whatever you want but you must ensure everyone else can do so as well". Then there's AGPL which is even stronger for deploying backend code.

**Comment by rkuykendall** [comment]
Thanks for your input TL. I think S7 is so low-value ( basically just a CRUD app ) that I'll go for MIT. I don't mind people stealing my trash code for their own non-GPL stuff.

**Comment by rkuykendall** [comment]
Thank you again @sfiera, S7 is now MIT licensed. Also I had to undo some of my clean-ups but I'm working on re-implementing them.
