### ISSUE TITLE
Search returns duplicated results

### ISSUE THREAD

**Issue by Iritscen** [rkuykendall/Simplici7y#29]
Some searches on S7 return certain mod pages multiple times.  For instance, if you search for "M1A1"…
https://simplici7y.com/?search=M1A1
…you will see some of the same results on page 2 as on page 1, including M1A1 Fixes and HardCore Sounds.

If you search for "NEFX"…
https://simplici7y.com/?search=NEFX
…you will see some maps again on the second page (Keyfinder and Pathsifter), and the very first result appears as the second result too, NEFX Mods.

Note: This is all assuming that search results are identical for everyone.  I can only give my own experience.

**Comment by rkuykendall** [comment]
They are identical and yes I see this issue as well. Looking into it.

**Comment by rkuykendall** [comment]
Thank you for this report @Iritscen! Fixed by https://github.com/rkuykendall/Simplici7y/commit/e635ce6e3c0b337688a9e230325e7faf2266a3c0, specifically the changes to how tags are searched which was causing the multiple results.
