### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by hrufusborg** [rkuykendall/Simplici7y#31]
tried to leave a review on Marathon Istoria on Simplici7y and received a bug report screen. #500.

**Comment by rkuykendall** [comment]
The good news is both your reviews made it in: https://simplici7y.com/items/marathon-istoria/

I will delete the second accidental one.

**Comment by rkuykendall** [comment]
Thank you for your bug report @hrufusborg! The bug has been found and the fix deployed.

**Comment by hrufusborg** [comment]
Thanks muchly for your help, it is really appreciated.
cura ut valeas.
bob.
