### ISSUE TITLE
Site experiencing "Congratulations, you found a bug!" 500 errors for long stretches of time.

### ISSUE THREAD

**Issue by lj6014** [rkuykendall/Simplici7y#5]

**Comment by Ethnik1** [comment]
And again.

**Comment by lj6014** [comment]
It's been doing this a lot lately

**Comment by pfhore-github** [comment]
And again.

**Comment by rkuykendall** [comment]
Hey I'm looking into this. I switched hosting a while back and the new server may be having trouble. Going to set an uptime-monitoring service on it and see what happens.

**Comment by barrettford** [comment]
Still broken...

**Comment by Lothster** [comment]
It's offline.

**Comment by rkuykendall** [comment]
It's down for the first time since I installed the uptime monitoring, which
notified me. Will look at it as soon as I can, and I'm also working on some
more stable hosting.

**Comment by brunocar** [comment]
its offline again

**Comment by rkuykendall** [comment]
Thanks. Working on more stable hosting, as well as getting the original hosting back up temporarily. These outages should be fixed soon.

**Comment by Zetren** [comment]
Any ETA as to when Simplici7y will be back online?

**Comment by rkuykendall** [comment]
Really sorry this delay has been longer than most, but hopefully it's the last. I just started a new job so it's been a busy week, and it's really just me working on this. My last session wasn't very successful, but I have an open weekend and will make sure the site is up by the end.

**Comment by rkuykendall** [comment]
Posting updates here: http://pfhorums.com/viewtopic.php?f=2&t=39824

**Comment by rkuykendall** [comment]
New server has been online and stable for 4 days. Closing!
